#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# fish
rm -rf $HOME/.config/fish
ln -s $DOTFILES/fish $HOME/.config/fish

# nvim
rm -rf $HOME/..local/share/nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim 

# alacritty
rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

