#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# nvim
rm -rf $HOME/..local/share/nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim 

rm -rf $HOME/.config/iterm
ln -s $DOTFILES/iterm $HOME/.config/iterm

